; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[common_env_data]
activate_spiram_buildflags =
	-D CONFIG_SPIRAM_CACHE_WORKAROUND
	-mfix-esp32-psram-cache-issue
	-D CONFIG_SPIRAM_SUPPORT=1
	-D CONFIG_SPIRAM_BOOT_INIT
	-D CONFIG_SPIRAM_TYPE_AUTO=1
	-D CONFIG_SPIRAM_SIZE=-1
	-D CONFIG_SPIRAM_SPEED_40M
	-D CONFIG_SPIRAM_MEMTEST=1
	-D CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
	-D CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
	-D CONFIG_SPIRAM_USE_MALLOC=1
	-D CONFIG_SUPPORT_STATIC_ALLOCATION=1
	-D CONFIG_PICO_PSRAM_CS_IO=10
	-D CONFIG_SPIRAM_OCCUPY_VSPI_HOST
	-D CONFIG_D0WD_PSRAM_CLK_IO=17
	-D CONFIG_D0WD_PSRAM_CS_IO=16
	-D CONFIG_D2WD_PSRAM_CLK_IO=9
	-D CONFIG_D2WD_PSRAM_CS_IO=10

#define CONFIG_SPIRAM_SPIWP_SD3_PIN 18

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
upload_port = /dev/ttyUSB0
upload_speed = 115200
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions.csv
build_flags =
	-D CONFIG_ESP_LYRATD_MSC_V2_2_BOARD
	${common_env_data.activate_spiram_buildflags}


; dependencies for this app
lib_deps = 
	components\esp-libhelix-mp3
	components\esp-audio-player
	components\usb_host_uac
	